on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: mac
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api https://api.github.com/repos/kulraj2swift/GithubList
